version: '3.0'
services:
    api:
        build: backend/.
        environment:
          - AUTHORITY=
        ports:
            - "8080:8080"

    webapp:
        build:
            context: frontend/.
            args:
              - AUTHORITY=
              - CLIENT_ID=
        ports:
            - "3000:80"

    opa:
        image: openpolicyagent/opa
        ports:
            - "8181:8181"
        command:
            - "run"
            - "--server"
